project_id = "yhlgoxjgbbwglxtietkc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
[functions.ai-medical-analysis]
verify_jwt = false