// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhlgoxjgbbwglxtietkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlobGdveGpnYmJ3Z2x4dGlldGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjI3MDMsImV4cCI6MjA3MjUzODcwM30.g6YVNwVHjoLSNQKJ74s1LQn9okzScuIgD6srVoe_iEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});